config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  resources :entries do
    resources :comments 
  end

  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :entry
end
 

app/models/entry.rb
class Entry < ApplicationRecord
  has_many :comments, dependent: :destroy
  validates :date, :text, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @entry = Entry.find(params[:entry_id])
    @comment = @entry.comments.create(comment_params)
    
    if @comment.save
      redirect_to entry_path(@entry)
    else
      @errors = @comment.errors.full_messages
      redirect_to entry_path(@entry)
    end
  end

  private
    def comment_params
      params.require(:comment).permit(:commenter, :body)
    end
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  def index
    @entries = Entry.all 
  end
  
  def show
    @entry = Entry.find(params[:id])
  end

  def new
    @entry = Entry.new
  end

  def edit
    @entry = Entry.find(params[:id])
  end

  def create
    @entry = Entry.new(entry_params)

    if @entry.save
      redirect_to @entry
    else
      @errors = @entry.errors.full_messages
      render 'new'
    end
  end

  def update
    @entry = Entry.find(params[:id])

    if @entry.update(entry_params)
      redirect_to @entry
    else
      @errors = @entry.errors.full_messages
      render 'edit'
    end
  end

  def destroy
    @entry = Entry.find(params[:id])
    @entry.destroy

    redirect_to entries_path
  end

  private
    def entry_params
      params.require(:entry).permit(:date, :text)
    end
end
 

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/comments/_comment.html.erb
<p>
  <strong>Commenter:</strong>
  <%= comment.commenter %>
</p>

<p>
  <strong>Comment:</strong>
  <%= comment.body %>
</p>

<p> 
  <%= link_to 'Delete', [comment.entry, comment],
               method: :delete,
               data: { confirm: 'Are you sure?'} %>
</p>

app/views/comments/_form.html.erb
<%= form_with(model: [ @entry, @entry.comments.build ], local: true) do |form| %>
  <p>
    <%= form.label :commenter %><br>
    <%= form.text_field :commenter %>
  </p>
  <p>
    <%= form.text_area :body, placeholder: "Leave a comment here" %>
  </p>

  <p><%= form.submit %></p>
<% end %>

app/views/entries/_errors.html.erb
  <% if @entry.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@entry.errors.count, "error") %> prohibited this entry from being saved:
      </h2>
      <ul>
        <% @errors.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

app/views/entries/_form.html.erb
<%= form_with model: @entry, local: true do |form| %>
  
<%= render 'errors' %>

  <p>
    <%= form.label :date %><br>
    <%= form.text_field :date %> 
  </p>

  <p>
    <%= form.text_area :text, placeholder: "Your entry here" %>
  </p>

  <p><%= form.submit %></p>

<% end %>

app/views/entries/edit.html.erb
<h1>Edit Entry</h1>

<%= render 'form' %>

<%= link_to 'Back', entries_path %>

app/views/entries/index.html.erb
<h1>All Entries</h1>

<table>
  <tr>
    <th>Date</th>
    <th>Entry</th>
  </tr>

  <% @entries.each do |entry| %>
    <tr>
      <td><%= entry.date %></td>
      <td><%= entry.text %></td>
      <td><%= link_to 'Show', entry_path(entry) %></td>
      <td><%= link_to 'Edit', edit_entry_path(entry) %></td>
      <td><%= link_to 'Delete', entry_path(entry),
              method: :delete,
              data: { confirm: 'Are you sure?'}  %></td>
    </tr>
  <% end %>
</table>

app/views/entries/new.html.erb
<h1>New Entry</h1>

<%= render 'form' %>

<%= link_to 'Back', entries_path %>

app/views/entries/show.html.erb
<p>
  <strong>Date:</strong>
  <%= @entry.date %>
</p>

<p>
  <strong>Entry:</strong>
  <%= @entry.text %>
</p>

<h2>Comments</h2>
<%= render @entry.comments %>

<h2>Add a comment:</h2>
<%= render 'comments/form' %>

<%= link_to 'Edit', edit_entry_path(@entry) %>
<%= link_to 'Back', entries_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JournalApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<h1>Hello, Rails!</h1>
<%= link_to 'My Journal', controller: 'entries' %>
<%= link_to 'New Entry', new_entry_path %>